//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devscord.DiscordFramework.Framework.Commands.BotCommandDescription {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devscord.DiscordFramework.Framework.Commands.BotCommandDescription.CommandDescrip" +
                            "tion", typeof(CommandDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an response that may appear.
        /// </summary>
        public static string AddResponseCommand {
            get {
                return ResourceManager.GetString("AddResponseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command allows you to add a role to the user.
        /// </summary>
        public static string AddRoleCommand {
            get {
                return ResourceManager.GetString("AddRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a warning to the user.
        /// </summary>
        public static string AddWarnCommand {
            get {
                return ResourceManager.GetString("AddWarnCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the user&apos;s avatar.
        /// </summary>
        public static string AvatarCommand {
            get {
                return ResourceManager.GetString("AvatarCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all custom commands.
        /// </summary>
        public static string CustomCommandsCommand {
            get {
                return ResourceManager.GetString("CustomCommandsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links to an article with the subject &quot;Don&apos;t ask, just ask&quot;.
        /// </summary>
        public static string DontaskCommand {
            get {
                return ResourceManager.GetString("DontaskCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for the appropriate phrase in google and generate a link..
        /// </summary>
        public static string GoogleCommand {
            get {
                return ResourceManager.GetString("GoogleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It displays all possible commands, or an example of using a specific command.
        /// </summary>
        public static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server initialization (loading information about the server into the bot database). It starts automatically when the bot is started, but if you have just added it to the server - it is possible that it has not been initialized yet - then it is worth doing it manually..
        /// </summary>
        public static string InitCommand {
            get {
                return ResourceManager.GetString("InitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer to life.
        /// </summary>
        public static string MarchewCommand {
            get {
                return ResourceManager.GetString("MarchewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this command if a person who is a demolisher of fun on your server.
        /// </summary>
        public static string MarudaCommand {
            get {
                return ResourceManager.GetString("MarudaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows some user&apos;s message histories.
        /// </summary>
        public static string MessagesCommand {
            get {
                return ResourceManager.GetString("MessagesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute the user on the server.
        /// </summary>
        public static string MuteCommand {
            get {
                return ResourceManager.GetString("MuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all muted users.
        /// </summary>
        public static string MutedUsersCommand {
            get {
                return ResourceManager.GetString("MutedUsersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts a link that explains why Don&apos;t just say hi in chat.
        /// </summary>
        public static string NoHelloCommand {
            get {
                return ResourceManager.GetString("NoHelloCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove response.
        /// </summary>
        public static string RemoveResponseCommand {
            get {
                return ResourceManager.GetString("RemoveResponseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command allows you to remove a role from a user.
        /// </summary>
        public static string RemoveRoleCommand {
            get {
                return ResourceManager.GetString("RemoveRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all possible respones.
        /// </summary>
        public static string ResponsesCommand {
            get {
                return ResourceManager.GetString("ResponsesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all safe roles on the server..
        /// </summary>
        public static string RolesCommand {
            get {
                return ResourceManager.GetString("RolesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display safe users.
        /// </summary>
        public static string SafeUsersCommand {
            get {
                return ResourceManager.GetString("SafeUsersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It allows you to send messages via bot to another text channel.
        /// </summary>
        public static string SendCommand {
            get {
                return ResourceManager.GetString("SendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds roles to the safe role list..
        /// </summary>
        public static string SetRoleCommand {
            get {
                return ResourceManager.GetString("SetRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a statistics graph showing the accuracy over a given period of time..
        /// </summary>
        public static string StatsCommand {
            get {
                return ResourceManager.GetString("StatsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role to trusted.
        /// </summary>
        public static string TrustCommand {
            get {
                return ResourceManager.GetString("TrustCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View trusted roles.
        /// </summary>
        public static string TrustedRolesCommand {
            get {
                return ResourceManager.GetString("TrustedRolesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute the user on the server.
        /// </summary>
        public static string UnmuteCommand {
            get {
                return ResourceManager.GetString("UnmuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role to untrusted.
        /// </summary>
        public static string UntrustCommand {
            get {
                return ResourceManager.GetString("UntrustCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update response.
        /// </summary>
        public static string UpdateResponseCommand {
            get {
                return ResourceManager.GetString("UpdateResponseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to check how many warnings a given user has.
        /// </summary>
        public static string WarnsCommand {
            get {
                return ResourceManager.GetString("WarnsCommand", resourceCulture);
            }
        }
    }
}
