name: Docker build and update

on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: docker build -t ${{ secrets.DOCKER_LOGIN }}/watchman-web . && docker login -p ${{ secrets.DOCKER_PASS }} -u ${{ secrets.DOCKER_LOGIN }} && docker push ${{ secrets.DOCKER_LOGIN }}/watchman-web:latest
